version: '3.0'
services:
  python:
    container_name: 'python.cpu.repo.skeleton'
    image: akitenkrad/python.cpu:latest
    platform: linux/amd64 # for Apple Mac M1
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
  
